server {
    listen 80;
    root /var/www/html;
    index index.html;

    location /api/ {
        fastcgi_pass dev-php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/api$uri;
    }

    location / {
        try_files $uri /index.html;
    }
}
